"use client"
import { useEffect,useMemo,useState } from "react"
import Link from "next/link"
import { useParams,useRouter } from "next/navigation"
import { api } from "@/lib/api"
import { Shell } from "@/components/workspace-shell"
import { Download,TrendingUp,CalendarDays,Activity,ShieldCheck,Stethoscope,Atom } from "lucide-react"

type Prediction={_id:string;assessmentId:string;condition:string;model:string;prediction:number;probability?:number;decisionScore?:number;assessmentProbability?:number;riskLevel?:string;createdAt:string;riskFactors?:string[];rawOutput?:any}
type Assessment={assessmentId:string;condition:string;createdAt:string;items:Prediction[];summary:{probability?:number|null;riskLevel:string}}
const MODEL_ORDER:Record<string,string[]>={cardiovascular:["RandomForest","XGBoost","SVM","HybridQuantum"],diabetes:["LogisticRegression","RandomForest","FinetunedHybridQML"]}
const modelLabel:Record<string,string>={RandomForest:"Random Forest",XGBoost:"XGBoost",SVM:"SVM (RBF)",HybridQuantum:"Hybrid Quantum",LogisticRegression:"Logistic Regression",FinetunedHybridQML:"Finetuned Hybrid QML"}
const conditionLabel:Record<string,string>={cardiovascular:"Cardiovascular",diabetes:"Diabetes"}
function pct(x?:number|null){return typeof x==="number"?`${(x*100).toFixed(1)}%`:"—"}
function band(x?:string){return x==="high"?"Higher":x==="moderate"?"Moderate":x==="low"?"Lower":"Unavailable"}
function Chart({assessments}:{assessments:Assessment[]}){const data=useMemo(()=>assessments.slice().reverse().filter(a=>typeof a.summary.probability==="number").slice(-7),[assessments]);if(data.length<2)return <div className="flex min-h-40 items-center justify-center rounded-xl border border-dashed bg-background/50 px-5 text-sm text-muted-foreground">A trend graph appears after two assessments with model-derived classical probability.</div>;const w=720,h=230,pad=34;const pts=data.map((a,i)=>{const value=a.summary.probability||0;return{x:pad+i*(w-pad*2)/Math.max(1,data.length-1),y:pad+(1-value)*(h-pad*2),value,label:new Date(a.createdAt).toLocaleDateString(undefined,{month:"short",day:"numeric"})}});return <div className="overflow-x-auto rounded-xl border bg-background/50 p-3 sm:p-5"><svg viewBox={`0 0 ${w} ${h}`} className="min-w-[620px] w-full" role="img" aria-label="Assessment probability trend"><line x1={pad} y1={pad} x2={pad} y2={h-pad} stroke="currentColor" strokeOpacity=".14"/><line x1={pad} y1={h-pad} x2={w-pad} y2={h-pad} stroke="currentColor" strokeOpacity=".14"/><text x="4" y={pad+4} className="fill-muted-foreground text-[11px]">100%</text><text x="8" y={h-pad+4} className="fill-muted-foreground text-[11px]">0%</text><polyline points={pts.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" className="text-primary"/>{pts.map((p,i)=><g key={i}><circle cx={p.x} cy={p.y} r="5" className="fill-background stroke-primary" strokeWidth="3"/><text x={p.x} y={h-9} textAnchor="middle" className="fill-muted-foreground text-[10px]">{p.label}</text><text x={p.x} y={p.y-10} textAnchor="middle" className="fill-foreground text-[10px]">{(p.value*100).toFixed(1)}%</text></g>)}</svg></div>}
function MetricTable({metrics}:{metrics:any}){const rows=Object.entries(metrics||{}) as [string,any][];if(!rows.length)return <p className="text-sm text-muted-foreground">Evaluation metrics for this condition have not been supplied in the model package.</p>;return <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="pb-3">Model</th><th className="pb-3">Accuracy</th><th className="pb-3">Sensitivity</th><th className="pb-3">Specificity</th><th className="pb-3">F1</th><th className="pb-3">ROC-AUC</th></tr></thead><tbody>{rows.map(([m,v])=><tr key={m} className="border-b last:border-0"><td className="py-3 font-medium">{modelLabel[m]||m}</td><td className="py-3">{(v.accuracy*100).toFixed(1)}%</td><td className="py-3">{(v.sensitivity*100).toFixed(1)}%</td><td className="py-3">{(v.specificity*100).toFixed(1)}%</td><td className="py-3">{(v.f1*100).toFixed(1)}%</td><td className="py-3">{v.roc_auc.toFixed(3)}</td></tr>)}</tbody></table></div>}

function QuantumArchitecture({condition}:{condition:string}){
  if(condition === "diabetes") return <div className="mt-5 rounded-xl border bg-background/60 p-4">
    <div className="flex flex-wrap items-center gap-2 text-xs font-semibold text-muted-foreground">
      <span className="rounded-full bg-muted px-2.5 py-1">4 qubits</span>
      <span className="rounded-full bg-muted px-2.5 py-1">3 layers</span>
      <span className="rounded-full bg-muted px-2.5 py-1">24 trainable parameters</span>
    </div>
    <div className="mt-4 grid grid-cols-5 gap-2 text-[11px] sm:text-xs">
      {["Feature encoding","Layer 1","Layer 2","Layer 3","Readout"].map((label,i)=><div key={label} className="rounded-lg border bg-card px-2 py-3 text-center font-medium">{label}{i>0&&i<4?<span className="mt-1 block text-muted-foreground">RY/RZ + CNOT</span>:null}</div>)}
    </div>
    <p className="mt-3 text-[11px] leading-relaxed text-muted-foreground">Runtime reconstruction from the supplied serialized artifact; the original QML training source was not bundled.</p>
  </div>
  return <div className="mt-5 rounded-xl border bg-background/60 p-4">
    <div className="flex flex-wrap items-center gap-2 text-xs font-semibold text-muted-foreground">
      <span className="rounded-full bg-muted px-2.5 py-1">6 quantum features</span>
      <span className="rounded-full bg-muted px-2.5 py-1">1 repetition</span>
      <span className="rounded-full bg-muted px-2.5 py-1">15,000 training vectors</span>
    </div>
    <div className="mt-4 grid grid-cols-4 gap-2 text-[11px] sm:text-xs">
      {["Selected features","Quantum feature map","Fidelity kernel","Classical SVM"].map(label=><div key={label} className="rounded-lg border bg-card px-2 py-3 text-center font-medium">{label}</div>)}
    </div>
    <p className="mt-3 text-[11px] leading-relaxed text-muted-foreground">Supplied cardiovascular hybrid model combining a classical branch with a quantum-kernel branch.</p>
  </div>
}
export default function Patient(){const {id}=useParams();const router=useRouter();const [d,setD]=useState<any>();const [error,setError]=useState("");const [downloading,setDownloading]=useState(false);const [metrics,setMetrics]=useState<any>();useEffect(()=>{if(id)api<any>(`/patients/${id}`).then(setD).catch(e=>{setError(e.message);if(e.message.includes("Authentication"))router.push("/login")})},[id,router]);useEffect(()=>{if(d?.viewerRole === "doctor" && d?.patient?.condition)api<any>(`/ml-info`).then(x=>setMetrics(x.conditions?.[d.patient.condition])).catch(()=>{})},[d?.viewerRole,d?.patient?.condition]);if(error)return <main className="min-h-screen bg-background"><Shell/><div className="mx-auto max-w-5xl px-5 py-10 text-sm text-destructive">{error}</div></main>;if(!d)return <main className="min-h-screen bg-background"><Shell/><div className="mx-auto max-w-5xl px-5 py-10 text-sm text-muted-foreground">Loading…</div></main>;const doctor=d.viewerRole==="doctor";const predictions:Prediction[]=d.predictions||[];const assessments:Assessment[]=d.assessments||[];const latest=assessments[0];const latestItems=latest?.items||[];const consensus=latest?.summary?.probability;const riskIndicators=d.riskIndicators||[];const condition=d.patient.condition||"cardiovascular";const order=MODEL_ORDER[condition];const performance=metrics?.production_test_set?.models||metrics?.test_set?.models||{};const fair=metrics?.fair_same_feature_benchmark?.models||{};async function downloadReport(){setDownloading(true);try{const r=await fetch(`/api/patients/${id}/report`,{credentials:"include"});if(!r.ok){const data=await r.json().catch(()=>null);throw new Error(data?.message||"Could not download report")}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`BioSync-${d.patient.patientId}-${condition}-analysis-report.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(e instanceof Error?e.message:"Could not download report")}finally{setDownloading(false)}}
return <main className="min-h-screen bg-background"><Shell/><div className="mx-auto max-w-5xl px-5 py-10"><Link href="/patients" className="text-sm text-muted-foreground">← Patients</Link><div className="mt-5 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-primary">{doctor?`${conditionLabel[condition]} patient assessment`:`Your ${conditionLabel[condition].toLowerCase()} assessment`}</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight">{d.patient.name}</h1><p className="mt-2 text-muted-foreground">{d.patient.patientId}</p></div>{doctor?<div className="flex flex-wrap gap-2"><Link href={`/patients/${id}/assessment`} className="inline-flex w-fit items-center gap-2 rounded-full bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground">Run assessment</Link><button onClick={downloadReport} disabled={downloading} className="inline-flex w-fit items-center gap-2 rounded-full border bg-card px-5 py-2.5 text-sm font-semibold shadow-sm hover:bg-muted disabled:opacity-60"><Download className="h-4 w-4"/>{downloading?"Preparing…":"Download analysis report"}</button></div>:<Link href={`/patients/${id}/assessment`} className="w-fit rounded-full bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground">New assessment</Link>}</div>
{doctor?<><section className="mt-8 grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><div className="rounded-2xl border bg-card p-6 shadow-sm"><div className="flex items-center gap-2 text-sm text-muted-foreground"><Activity className="h-4 w-4"/> Model-derived {conditionLabel[condition].toLowerCase()} risk band</div><div className="mt-3 flex items-end justify-between gap-4"><div><p className="text-4xl font-semibold">{typeof consensus==="number"?pct(consensus):"—"}</p><p className="mt-1 text-sm text-muted-foreground">Hybrid model output when available; otherwise average classical-model output. Not a clinically validated probability.</p></div><span className="rounded-full border px-3 py-1 text-xs font-semibold">{band(latest?.summary?.riskLevel)}</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${typeof consensus==="number"?Math.max(0,Math.min(100,consensus*100)):0}%`}}/></div></div><div className="rounded-2xl border bg-card p-6 shadow-sm"><div className="flex items-center gap-2 text-sm text-muted-foreground"><ShieldCheck className="h-4 w-4"/> Assessment snapshot</div><div className="mt-5 space-y-4"><div><p className="text-xs text-muted-foreground">Models run</p><p className="mt-1 font-semibold">{latestItems.length||0} / {order.length}</p></div><div><p className="text-xs text-muted-foreground">Last assessed</p><p className="mt-1 font-semibold">{latest?new Date(latest.createdAt).toLocaleString():"—"}</p></div><div><p className="text-xs text-muted-foreground">Models completed</p><p className="mt-1 font-semibold">{latestItems.length||0} / {order.length}</p></div></div></div></section>
<section className="mt-8 rounded-2xl border bg-card p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">Model comparison</h2><p className="mt-1 text-sm text-muted-foreground">Each model reports its own trained prediction for the same submitted patient record.</p></div><TrendingUp className="h-5 w-5 text-muted-foreground"/></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="pb-3">Model</th><th className="pb-3">Prediction</th><th className="pb-3">Probability / score</th><th className="pb-3">Result</th></tr></thead><tbody>{order.map(name=>{const x=latestItems.find(p=>p.model===name);return <tr key={name} className="border-b last:border-0"><td className="py-4 font-medium">{modelLabel[name]}</td><td className="py-4">{x?x.prediction===1?"Positive":"Negative":"Not run"}</td><td className="py-4">{x?typeof x.probability==="number"?pct(x.probability):typeof x.decisionScore==="number"?`Decision ${x.decisionScore.toFixed(3)}`:"Not probabilistic":"—"}</td><td className="py-4 text-muted-foreground">{x?"Completed":"Unavailable"}</td></tr>})}</tbody></table></div><p className="mt-4 text-xs text-muted-foreground">Positive/negative is a model class label. It is not a diagnosis.</p></section>
<section className="mt-8 rounded-2xl border bg-card p-6 shadow-sm"><div className="flex items-center justify-between gap-4"><div><h2 className="font-semibold">Hybrid quantum-classical result</h2><p className="mt-1 text-sm text-muted-foreground">Hybrid quantum model output for this assessment.</p></div><Atom className="h-5 w-5 text-muted-foreground"/></div>{(() => { const q=latestItems.find(p=>p.model===(condition==="diabetes"?"FinetunedHybridQML":"HybridQuantum")); return q ? <div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs text-muted-foreground">Prediction</p><p className="mt-1 text-2xl font-semibold">{q.prediction===1?"Positive":"Negative"}</p></div><div className="text-right"><p className="text-xs text-muted-foreground">{typeof q.probability==="number"?"Model score":"Decision score"}</p><p className="mt-1 font-semibold">{typeof q.probability==="number"?pct(q.probability):typeof q.decisionScore==="number"?q.decisionScore.toFixed(3):"—"}</p></div></div> : <div className="mt-5 rounded-xl border border-dashed bg-background/50 p-4 text-sm text-muted-foreground">The quantum model did not return a result for this assessment. Run the assessment again after checking the model service.</div> })()}</section>
<section className="mt-8 rounded-2xl border bg-card p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">Evaluation evidence</h2><p className="mt-1 text-sm text-muted-foreground">Held-out test-set evidence. For the quantum comparison, BioSync uses the same four numeric features and the same 1,000-row test split.</p></div></div>{condition==="diabetes"&&Object.keys(fair).length?<><div className="mt-5"><h3 className="font-semibold">Direct classical vs hybrid-QML benchmark</h3><p className="mt-1 text-sm text-muted-foreground">Same feature space: Age, BMI, HbA1c and blood glucose. Test set: 1,000 rows with 8.5% positive cases. The supplied QML metrics are kept as source evidence; the classical baselines were independently retrained from the supplied training split.</p><div className="mt-4"><MetricTable metrics={fair}/></div></div><div className="mt-7 border-t pt-6"><h3 className="font-semibold">Production classical baselines</h3><p className="mt-1 text-sm text-muted-foreground">These use the full eight-feature Diabetes production input contract and are intentionally kept separate from the direct quantum comparison.</p><div className="mt-4"><MetricTable metrics={performance}/></div></div></>:<div className="mt-5"><MetricTable metrics={performance}/></div>}<p className="mt-4 text-xs text-muted-foreground">Accuracy is not interpreted alone because the supplied test set is imbalanced. Sensitivity, specificity, F1 and ROC-AUC are reported together.</p></section>
<section className="mt-8 rounded-2xl border bg-card p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">Assessment trend</h2><p className="mt-1 text-sm text-muted-foreground">Model-derived assessment probability across assessments.</p></div><CalendarDays className="h-5 w-5 text-muted-foreground"/></div><div className="mt-5"><Chart assessments={assessments}/></div></section>
<section className="mt-8 rounded-2xl border bg-card p-6 shadow-sm"><h2 className="font-semibold">Relevant submitted-value indicators</h2><p className="mt-1 text-sm text-muted-foreground">These are derived directly from entered patient values; they are not model-attribution scores.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{riskIndicators.length?riskIndicators.map((f:string)=><div key={f} className="rounded-xl border bg-background/60 px-4 py-3 text-sm font-medium">{f}</div>):<p className="text-sm text-muted-foreground">No prominent indicators were identified from the submitted fields.</p>}</div></section>
<section className="mt-8 rounded-2xl border bg-card p-6 shadow-sm"><h2 className="font-semibold">Assessment history</h2><div className="mt-4 divide-y">{assessments.slice(0,8).map(a=><div key={a.assessmentId} className="flex flex-col gap-1 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium">{new Date(a.createdAt).toLocaleString()}</p><p className="text-xs text-muted-foreground">{a.items.map(x=>modelLabel[x.model]||x.model).join(" · ")}</p></div><span className="rounded-full bg-muted px-3 py-1 text-xs font-semibold">{band(a.summary.riskLevel)}</span></div>)}{!assessments.length&&<p className="py-5 text-sm text-muted-foreground">No assessments yet.</p>}</div></section>
</>:<section className="mt-8 rounded-2xl border bg-card p-7 shadow-sm"><p className="text-sm font-semibold text-primary">Assessment completed</p><h2 className="mt-3 text-2xl font-semibold">{latest?.summary?.riskLevel?`${band(latest.summary.riskLevel)} model-derived risk band`:"No assessment yet"}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{latest?"Your assessment has been processed. The detailed model comparison is available only to the authorized professional reviewing this patient record.":"Complete an assessment when you are ready."}</p>{latest&&<div className="mt-5 inline-flex items-center gap-2 rounded-full border bg-background px-5 py-2.5 text-sm font-semibold"><Stethoscope className="h-4 w-4"/> Consult a healthcare professional</div>}</section>}</div></main>}
